# default ingress port
servicePort: 80

# ingress
ingressEnabled: true

# configure redis
redis:
  usePassword: false
  redisPassword: ""

# postgresql
postgresql:
  postgresPassword: "demo"

result:
  imageTag: javago