{{- if .Values.ingressEnabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/redirect-to-https: "false"
  name: {{ template "fullname" . }}-ingress
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
spec:
  rules:
  - host: vote.demo.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-vote
          servicePort: {{ .Values.servicePort }}
  - host: result.demo.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-result
          servicePort: {{ .Values.servicePort }}
{{- end -}}
